# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import db_pb2 as db__pb2


class BlockChainMinerStub(object):
  """Interface exported by the server.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Get = channel.unary_unary(
        '/blockdb.BlockChainMiner/Get',
        request_serializer=db__pb2.GetRequest.SerializeToString,
        response_deserializer=db__pb2.GetResponse.FromString,
        )
    self.Transfer = channel.unary_unary(
        '/blockdb.BlockChainMiner/Transfer',
        request_serializer=db__pb2.Transaction.SerializeToString,
        response_deserializer=db__pb2.BooleanResponse.FromString,
        )
    self.Verify = channel.unary_unary(
        '/blockdb.BlockChainMiner/Verify',
        request_serializer=db__pb2.Transaction.SerializeToString,
        response_deserializer=db__pb2.VerifyResponse.FromString,
        )
    self.GetHeight = channel.unary_unary(
        '/blockdb.BlockChainMiner/GetHeight',
        request_serializer=db__pb2.Null.SerializeToString,
        response_deserializer=db__pb2.GetHeightResponse.FromString,
        )
    self.GetBlock = channel.unary_unary(
        '/blockdb.BlockChainMiner/GetBlock',
        request_serializer=db__pb2.GetBlockRequest.SerializeToString,
        response_deserializer=db__pb2.JsonBlockString.FromString,
        )
    self.PushBlock = channel.unary_unary(
        '/blockdb.BlockChainMiner/PushBlock',
        request_serializer=db__pb2.JsonBlockString.SerializeToString,
        response_deserializer=db__pb2.Null.FromString,
        )
    self.PushTransaction = channel.unary_unary(
        '/blockdb.BlockChainMiner/PushTransaction',
        request_serializer=db__pb2.Transaction.SerializeToString,
        response_deserializer=db__pb2.Null.FromString,
        )


class BlockChainMinerServicer(object):
  """Interface exported by the server.
  """

  def Get(self, request, context):
    """Return UserID's Balance on the Chain, after considering the latest valid block. Pending transactions have no effect on Get()
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Transfer(self, request, context):
    """Receive and Broadcast Transaction: balance[FromID]-=Value, balance[ToID]+=(Value-MiningFee), balance[MinerID]+=MiningFee
    Return Success=false if FromID is same as ToID or latest balance of FromID is insufficient
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Verify(self, request, context):
    """Check if a transaction has been written into a block, or is still waiting, or is invalid on the longest branch.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetHeight(self, request, context):
    """Get the current blockchain length; use the longest branch if multiple branch exist.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBlock(self, request, context):
    """Get the Json representation of the block with BlockHash hash value
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PushBlock(self, request, context):
    """Send a block to another server
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PushTransaction(self, request, context):
    """Send a transaction to another server
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BlockChainMinerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Get': grpc.unary_unary_rpc_method_handler(
          servicer.Get,
          request_deserializer=db__pb2.GetRequest.FromString,
          response_serializer=db__pb2.GetResponse.SerializeToString,
      ),
      'Transfer': grpc.unary_unary_rpc_method_handler(
          servicer.Transfer,
          request_deserializer=db__pb2.Transaction.FromString,
          response_serializer=db__pb2.BooleanResponse.SerializeToString,
      ),
      'Verify': grpc.unary_unary_rpc_method_handler(
          servicer.Verify,
          request_deserializer=db__pb2.Transaction.FromString,
          response_serializer=db__pb2.VerifyResponse.SerializeToString,
      ),
      'GetHeight': grpc.unary_unary_rpc_method_handler(
          servicer.GetHeight,
          request_deserializer=db__pb2.Null.FromString,
          response_serializer=db__pb2.GetHeightResponse.SerializeToString,
      ),
      'GetBlock': grpc.unary_unary_rpc_method_handler(
          servicer.GetBlock,
          request_deserializer=db__pb2.GetBlockRequest.FromString,
          response_serializer=db__pb2.JsonBlockString.SerializeToString,
      ),
      'PushBlock': grpc.unary_unary_rpc_method_handler(
          servicer.PushBlock,
          request_deserializer=db__pb2.JsonBlockString.FromString,
          response_serializer=db__pb2.Null.SerializeToString,
      ),
      'PushTransaction': grpc.unary_unary_rpc_method_handler(
          servicer.PushTransaction,
          request_deserializer=db__pb2.Transaction.FromString,
          response_serializer=db__pb2.Null.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'blockdb.BlockChainMiner', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
